# Generated by Django 5.2.9 on 2025-12-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehicle_last_latitude_vehicle_last_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_heading',
            field=models.FloatField(default=0.0),
        ),
    ]
