# Generated by Django 5.2.7 on 2025-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vehicleposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_debt',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
