# Generated by Django 5.2.7 on 2025-12-12 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_current_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destinations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='surat_jalan_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SuratJalanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surat_jalan_number', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surat_histories', to='core.trip')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
