# Generated by Django 5.2.7 on 2025-12-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trip_destinations_trip_surat_jalan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='completed_destinations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
