# Generated by Django 5.2.9 on 2025-12-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trip_completed_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='standard_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='drop_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='drop_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='proof_of_delivery',
            field=models.ImageField(blank=True, null=True, upload_to='pod/'),
        ),
    ]
