# Generated by Django 5.2.9 on 2025-12-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_deliveryproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
