# Generated by Django 5.2.9 on 2025-12-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organization_subscription_end_date_organization_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('FINANCE', 'Finance'), ('DRIVER', 'Driver')], default='ADMIN', max_length=10),
        ),
    ]
