# Generated by Django 5.2.9 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_trip_price_trip_driver_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='cash_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='final_odometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('OTW', 'On The Way'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SETTLED', 'Settled')], default='PLANNED', max_length=20),
        ),
    ]
