# Generated by Django 5.2.9 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_trip_driver_commission_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_fuel_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='route',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
