# Generated by Django 5.2.7 on 2025-12-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notification_alert_key_notification_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='driver_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited drivers'),
        ),
    ]
