# Generated by Django 5.2.7 on 2025-12-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_organization_driver_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='vehicle_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited vehicles'),
        ),
    ]
