# Generated by Django 5.2.7 on 2025-12-17 12:24

from django.db import migrations, models
from django.utils import timezone


def forwards_migrate_invoice_data(apps, schema_editor):
    """
    - Move Invoice.trips (M2M) -> Trip.invoice (FK)
    - Normalize Invoice.status values to lowercase
    - Populate Invoice.invoice_number for existing rows
    """
    Invoice = apps.get_model('finance', 'Invoice')
    Trip = apps.get_model('core', 'Trip')

    status_map = {
        'DRAFT': 'draft',
        'SENT': 'sent',
        'PAID': 'paid',
        'OVERDUE': 'overdue',
    }
    for old, new in status_map.items():
        Invoice.objects.filter(status=old).update(status=new)

    # Copy invoice-trip relationship into FK.
    for invoice in Invoice.objects.all().iterator():
        trip_ids = list(invoice.trips.values_list('id', flat=True))
        if trip_ids:
            Trip.objects.filter(id__in=trip_ids, invoice__isnull=True).update(invoice_id=invoice.id)

    # Generate invoice numbers for existing invoices (per year sequence).
    next_seq_by_year = {}
    for invoice in Invoice.objects.all().order_by('created_at', 'id').iterator():
        if invoice.invoice_number:
            continue
        created_date = invoice.created_at.date() if invoice.created_at else timezone.localdate()
        year = created_date.year

        next_seq = next_seq_by_year.get(year)
        if next_seq is None:
            prefix = f"INV-{year}"
            last_invoice = (
                Invoice.objects.filter(invoice_number__startswith=prefix)
                .exclude(invoice_number__isnull=True)
                .exclude(invoice_number='')
                .order_by('-invoice_number')
                .first()
            )
            next_seq = 1
            if last_invoice and last_invoice.invoice_number:
                suffix = last_invoice.invoice_number.replace(prefix, '')
                if suffix.isdigit():
                    next_seq = int(suffix) + 1

        invoice.invoice_number = f"INV-{year}{next_seq:03d}"
        invoice.save(update_fields=['invoice_number'])
        next_seq_by_year[year] = next_seq + 1


def backwards_migrate_invoice_data(apps, schema_editor):
    """
    Best-effort rollback: restore Trip.invoice -> Invoice.trips M2M.
    """
    Invoice = apps.get_model('finance', 'Invoice')
    Trip = apps.get_model('core', 'Trip')

    for invoice in Invoice.objects.all().iterator():
        trips = Trip.objects.filter(invoice_id=invoice.id)
        if trips.exists():
            invoice.trips.add(*trips)
    Trip.objects.filter(invoice__isnull=False).update(invoice=None)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('core', '0017_trip_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=10),
        ),
        migrations.RunPython(forwards_migrate_invoice_data, backwards_migrate_invoice_data),
        migrations.RemoveField(
            model_name='invoice',
            name='trips',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
