# Generated by Django 5.2.9 on 2025-12-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('gps_device_id', models.CharField(max_length=50)),
                ('last_latitude', models.FloatField()),
                ('last_longitude', models.FloatField()),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Client Vehicle',
                'verbose_name_plural': 'Client Vehicles',
                'db_table': 'core_vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'core_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'core_organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('destinations', models.JSONField(blank=True, default=list)),
                ('completed_destinations', models.JSONField(blank=True, default=list)),
                ('cargo_type', models.CharField(blank=True, max_length=50)),
                ('surat_jalan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('allowance_given', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('actual_fuel_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('actual_fuel_liters', models.FloatField(default=0)),
                ('actual_toll_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('unloading_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('other_expense', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField()),
                ('role', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('current_debt', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'core_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('gps_device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('last_latitude', models.FloatField(default=0.0)),
                ('last_longitude', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField()),
                ('last_heading', models.FloatField(default=0.0)),
                ('last_speed', models.FloatField(default=0.0)),
                ('last_ignition', models.BooleanField(default=False)),
                ('current_odometer', models.IntegerField(default=0)),
                ('last_service_odometer', models.IntegerField(default=0)),
                ('stnk_expiry', models.DateField(blank=True, null=True)),
                ('kir_expiry', models.DateField(blank=True, null=True)),
                ('tax_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_vehicle',
                'managed': False,
            },
        ),
    ]
